// Generated by /Users/tm/workspaces/bin/sync-security.py - DO NOT EDIT MANUALLY.
// src/lib/security/sentry-tags.ts
//
// Helper pro tagovani security eventu do Sentry.
// Funguje aj bez Sentry SDK - tise loguje na server console (no-op fallback).

type SecurityEventKind =
  | "honeypot.hit"
  | "rate_limited"
  | "bot.detected"
  | "csp_violation"
  | "auth.brute_force"
  | "scrape.suspected";

interface SecurityEventMeta {
  ip?: string;
  userAgent?: string;
  referer?: string;
  path?: string;
  reason?: string;
  [key: string]: string | undefined;
}

export async function tagSecurityEvent(
  kind: SecurityEventKind,
  meta: SecurityEventMeta,
): Promise<void> {
  // Sentry SDK is intentionally NOT installed in this project (it crashes the
  // Vercel build without a DSN). Security events go to the server console,
  // which Vercel Functions logs capture and can be alerted on.
  console.warn(
    JSON.stringify({
      kind: `security:${kind}`,
      ts: new Date().toISOString(),
      ...meta,
    }),
  );
}
